//  copyright lexilogos.com

(function() {
    const textarea = document.getElementById("bar");

    const replacements = [
//kata
[/([A-Z])([a-z])/g, function(match, p1, p2) {
    return p1 + p2.toUpperCase();
}],
	
[/[ÔŌ]/g, "Oー"],
[/[ŪÛ]/g, "Uー"],
[/[ÂĀ]/g, "Aー"],
[/[ÎĪ]/g, "Iー"],
[/[ÊĒ]/g, "Eー"],
[/_/g, "ー"],

[/N/g, "ン"],
[/V/g, "ヴ"],
[/Q/g, "ッ"],
[/([BDFGHJKLMPQRSTVWXZ])\1/g, "ッ$1"],
[/KYA/g, "キャ"],
[/KYU/g, "キュ"],
[/KYO/g, "キョ"],
[/ンYA/g, "ニャ"],
[/ンYU/g, "ニュ"],
[/ンYO/g, "ニョ"],
[/SHA/g, "シャ"],
[/SHU/g, "シュ"],
[/SHO/g, "ショ"],
[/CHA/g, "チャ"],
[/CHU/g, "チュ"],
[/CHO/g, "チョ"],
[/HYA/g, "ヒャ"],
[/HYU/g, "ヒュ"],
[/HYO/g, "ヒョ"],
[/MYA/g, "ミャ"],
[/MYU/g, "ミュ"],
[/MYO/g, "ミョ"],
[/RYA/g, "リャ"],
[/RYU/g, "リュ"],
[/RYO/g, "リョ"],
[/GYA/g, "ギャ"],
[/GYU/g, "ギュ"],
[/GYO/g, "ギョ"],
[/BYA/g, "ビャ"],
[/BYU/g, "ビュ"],
[/BYO/g, "ビョ"],
[/PYA/g, "ピャ"],
[/PYU/g, "ピュ"],
[/PYO/g, "ピョ"],
[/JA/g, "ジャ"],
[/JU/g, "ジュ"],
[/JO/g, "ジョ"],

[/TSU/g, "ツ"],
[/DZU/g, "ヅ"], 
[/DJU/g, "ヅ"],
[/DJI/g, "ヂ"],
[/SHI/g, "シ"],
[/CHI/g, "チ"],

// supplements
[/JE/g, "ジェ"],
[/TI/g, "ティ"],
[/TU/g, "トゥ"],
[/TYU/g, "テュ"],
[/DI/g, "ディ"],
[/DU/g, "ドゥ"],
[/DYU/g, "デュ"],
[/SI/g, "スィ"],
[/ZI/g, "ズィ"],
[/SHE/g, "ジェ"],
[/CHE/g, "チェ"],
[/TSA/g, "ツァ"],
[/TSI/g, "ツィ"],
[/TSE/g, "ツェ"],
[/TSO/g, "ツォ"],
[/FA/g, "ファ"],
[/FI/g, "フィ"],
[/FE/g, "フェ"],
[/FO/g, "フォ"],
[/FYU/g, "フュ"],
[/HU/g, "ホゥ"],
[/YE/g, "イェ"],
[/YI/g, "イィ"],
[/WU/g, "ウゥ"],



[/BA/g, "バ"],
[/DA/g, "ダ"],
[/GA/g, "ガ"],
[/HA/g, "ハ"],
[/KA/g, "カ"],
[/MA/g, "マ"],
[/ンA/g, "ナ"],
[/PA/g, "パ"],
[/RA/g, "ラ"],
[/SA/g, "サ"],
[/TA/g, "タ"],
[/WA/g, "ワ"],
[/YA/g, "ヤ"],
[/ZA/g, "ザ"],
[/BE/g, "ベ"],
[/DE/g, "デ"],
[/GE/g, "ゲ"],
[/HE/g, "ヘ"],
[/KE/g, "ケ"],
[/ME/g, "メ"],
[/ンE/g, "ネ"],
[/PE/g, "ペ"],
[/RE/g, "レ"],
[/SE/g, "セ"],
[/TE/g, "テ"],
[/WE/g, "ヱ"],
[/ZE/g, "ゼ"],
[/BI/g, "ビ"],
[/GI/g, "ギ"],
[/HI/g, "ヒ"],
[/KI/g, "キ"],
[/MI/g, "ミ"],
[/ンI/g, "ニ"],
[/PI/g, "ピ"],
[/RI/g, "リ"],
[/WI/g, "ヰ"],
[/JI/g, "ジ"],
[/BO/g, "ボ"],
[/DO/g, "ド"],
[/GO/g, "ゴ"],
[/HO/g, "ホ"],
[/KO/g, "コ"],
[/MO/g, "モ"],
[/ンO/g, "ノ"],
[/PO/g, "ポ"],
[/RO/g, "ロ"],
[/SO/g, "ソ"],
[/TO/g, "ト"],
[/WO/g, "ヲ"],
[/YO/g, "ヨ"],
[/ZO/g, "ゾ"],
[/BU/g, "ブ"],
[/GU/g, "グ"],
[/FU/g, "フ"],
[/KU/g, "ク"],
[/MU/g, "ム"],
[/ンU/g, "ヌ"],
[/PU/g, "プ"],
[/RU/g, "ル"],
[/SU/g, "ス"],
[/YU/g, "ユ"],
[/ZU/g, "ズ"],


//archaic
//[/YE/g, "𛄡"],
//[/YI/g, "𛄠"],
//[/WU/g, "𛄢"],

[/A/g, "ア"],
[/[EÉ]/g, "エ"],
[/I/g, "イ"],
[/O/g, "オ"],
[/U/g, "ウ"],

[/ア=/g, "ァ"],
[/イ=/g, "ィ"],
[/ウ=/g, "ゥ"],
[/エ=/g, "ェ"],
[/オ=/g, "ォ"],
[/ツ=/g, "ッ"],
[/ヤ=/g, "ャ"],
[/ユ=/g, "ュ"],
[/ヨ=/g, "ョ"],

[/ァ=/g, "ア"],
[/ィ=/g, "イ"],
[/ゥ=/g, "ウ"],
[/ェ=/g, "エ"],
[/ォ=/g, "オ"],
[/ッ=/g, "ツ"],
[/ャ=/g, "ヤ"],
[/ュ=/g, "ユ"],
[/ョ=/g, "ヨ"],

// 2e série
[/ク=/g, "ㇰ"],
[/シ=/g, "ㇱ"],
[/ス=/g, "ㇲ"],
[/ト=/g, "ㇳ"],
[/ヌ=/g, "ㇴ"],
[/ハ=/g, "ㇵ"],
[/ヒ=/g, "ㇶ"],
[/フ=/g, "ㇷ"],
[/ヘ=/g, "ㇸ"],
[/ホ=/g, "ㇹ"],
[/ム=/g, "ㇺ"],
[/ラ=/g, "ㇻ"],
[/リ=/g, "ㇼ"],
[/ル=/g, "ㇽ"],
[/レ=/g, "ㇾ"],
[/ロ=/g, "ㇿ"],

[/ㇰ=/g, "ク"],
[/ㇱ=/g, "シ"],
[/ㇲ=/g, "ス"],
[/ㇳ=/g, "ト"],
[/ㇴ=/g, "ヌ"],
[/ㇵ=/g, "ハ"],
[/ㇶ=/g, "ヒ"],
[/ㇷ=/g, "フ"],
[/ㇸ=/g, "ヘ"],
[/ㇹ=/g, "ホ"],
[/ㇺ=/g, "ム"],
[/ㇻ=/g, "ラ"],
[/ㇼ=/g, "リ"],
[/ㇽ=/g, "ル"],
[/ㇾ=/g, "レ"],
[/ㇿ=/g, "ロ"],
// ka ke
[/カ=/g, "ヵ"],
[/ヵ=/g, "カ"],
[/ケ=/g, "ヶ"],
[/ヶ=/g, "ケ"],


[/[ôō]/g, "oう"],
[/[ūû]/g, "uう"],
[/[âā]/g, "aあ"],
[/[îī]/g, "iい"],
[/[êē]/g, "eい"],

[/n/g, "ん"],
[/q/g, "っ"],
[/([bdfghjklmpqrstvwxz])\1/g, "っ$1"],
[/tsu/g, "つ"],
[/dzu/g, "づ"],
[/dji/g, "ぢ"],
[/kya/g, "きゃ"],
[/kyu/g, "きゅ"],
[/kyo/g, "きょ"],
[/んya/g, "にゃ"],
[/んyu/g, "にゅ"],
[/んyo/g, "にょ"],
[/sha/g, "しゃ"],
[/shi/g, "し"],
[/shu/g, "しゅ"],
[/sho/g, "しょ"],
[/chi/g, "ち"],
[/cha/g, "ちゃ"],
[/chu/g, "ちゅ"],
[/cho/g, "ちょ"],
[/hya/g, "ひゃ"],
[/hyu/g, "ひゅ"],
[/hyo/g, "ひょ"],
[/mya/g, "みゃ"],
[/myu/g, "みゅ"],
[/myo/g, "みょ"],
[/rya/g, "りゃ"],
[/ryu/g, "りゅ"],
[/ryo/g, "りょ"],
[/gya/g, "ぎゃ"],
[/gyu/g, "ぎゅ"],
[/gyo/g, "ぎょ"],
[/bya/g, "びゃ"],
[/byu/g, "びゅ"],
[/byo/g, "びょ"],
[/pya/g, "ぴゃ"],
[/pyu/g, "ぴゅ"],
[/pyo/g, "ぴょ"],
[/ja/g, "じゃ"],
[/ju/g, "じゅ"],
[/jo/g, "じょ"],
[/ba/g, "ば"],
[/da/g, "だ"],
[/ga/g, "が"],
[/ha/g, "は"],
[/ka/g, "か"],
[/ma/g, "ま"],
[/んa/g, "な"],
[/pa/g, "ぱ"],
[/ra/g, "ら"],
[/sa/g, "さ"],
[/ta/g, "た"],
[/wa/g, "わ"],
[/ya/g, "や"],
[/za/g, "ざ"],
[/be/g, "べ"],
[/de/g, "で"],
[/ge/g, "げ"],
[/he/g, "へ"],
[/ke/g, "け"],
[/me/g, "め"],
[/んe/g, "ね"],
[/pe/g, "ぺ"],
[/re/g, "れ"],
[/se/g, "せ"],
[/te/g, "て"],
[/we/g, "ゑ"],
[/ze/g, "ぜ"],
[/bi/g, "び"],
[/gi/g, "ぎ"],
[/hi/g, "ひ"],
[/ki/g, "き"],
[/si/g, "し"],
[/ti/g, "ち"],
[/mi/g, "み"],
[/んi/g, "に"],
[/pi/g, "ぴ"],
[/ri/g, "り"],
[/wi/g, "ゐ"],
[/ji/g, "じ"],
[/zi/g, "じ"],
[/bo/g, "ぼ"],
[/do/g, "ど"],
[/go/g, "ご"],
[/ho/g, "ほ"],
[/ko/g, "こ"],
[/mo/g, "も"],
[/んo/g, "の"],
[/po/g, "ぽ"],
[/ro/g, "ろ"],
[/so/g, "そ"],
[/to/g, "と"],
[/wo/g, "を"],
[/yo/g, "よ"],
[/zo/g, "ぞ"],
[/bu/g, "ぶ"],
[/gu/g, "ぐ"],
[/fu/g, "ふ"],
[/hu/g, "ふ"],
[/ku/g, "く"],
[/mu/g, "む"],
[/んu/g, "ぬ"],
[/pu/g, "ぷ"],
[/ru/g, "る"],
[/su/g, "す"],
[/tu/g, "つ"], 
[/yu/g, "ゆ"],
[/zu/g, "ず"],

// cas des doublons
[/di/g, "ぢ"],
[/じ=/g, "ぢ"],
[/du/g, "づ"],
[/ず=/g, "づ"],

[/a/g, "あ"],
[/[eé]/g, "え"],
[/i/g, "い"],
[/o/g, "お"],
[/u/g, "う"],
[/v/g, "ゔ"],

[/つ=/g, "っ"],
[/あ=/g, "ぁ"],
[/い=/g, "ぃ"],
[/う=/g, "ぅ"],
[/え=/g, "ぇ"],
[/お=/g, "ぉ"],
[/や=/g, "ゃ"],
[/ゆ=/g, "ゅ"],
[/よ=/g, "ょ"],

[/っ=/g, "つ"],
[/ぁ=/g, "あ"],
[/ぃ=/g, "い"],
[/ぅ=/g, "う"],
[/ぇ=/g, "え"],
[/ぉ=/g, "お"],
[/ゃ=/g, "や"],
[/ゅ=/g, "ゆ"],
[/ょ=/g, "よ"],
// ka ke
[/か=/g, "ゕ"],
[/ゕ=/g, "か"],
[/け=/g, "ゖ"],
[/ゖ=/g, "け"],

//ponctuation
[/\./g, "。"],
[/,/g, "、"],
[/\!/g, "！"],
[/\?/g, "？"],
[/\:/g, "："],
[/\(/g, "（"],
[/\)/g, "）"],
[/\[/g, "［"],
[/\]/g, "］"],
[/«/g, "「"],
[/»/g, "」"],
];

    const transform = (txt) => {
        let result = txt;
        for (const [regex, replacement] of replacements) {
            result = result.replace(regex, replacement);
        }
        return result;
    };

    textarea.addEventListener("input", (e) => {
        const start = textarea.selectionStart;
        const end = textarea.selectionEnd;
        const scrollTop = textarea.scrollTop;

        const originalText = textarea.value;

        if (start === 0 && end === originalText.length) {
            textarea.value = transform(originalText);
            textarea.selectionStart = 0;
            textarea.selectionEnd = textarea.value.length;
        }
        else {
            textarea.value = transform(originalText);

            let beforeCursorOriginal = originalText.substring(0, start);
            beforeCursorOriginal = transform(beforeCursorOriginal);
            textarea.selectionStart = textarea.selectionEnd = beforeCursorOriginal.length;
        }

        textarea.scrollTop = scrollTop;
    });


    textarea.addEventListener("keydown", (e) => {
        if (e.ctrlKey || e.metaKey) {
            return;
        }
    });

})();